[versions]
accompanistPermissions = "0.37.3"
agp = "8.12.1"
android-compileSdk = "36"
android-minSdk = "24"
#noinspection OldTargetApi
android-targetSdk = "35"
androidDriver = "2.1.0"
androidWaveRecorder = "2.1.0"
androidx-activity = "1.10.1"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.2"
androidx-testExt = "1.3.0"
audioWaveform = "1.1.1"
cameraCamera2 = "1.4.2"
composeMultiplatform = "1.8.2"
firebaseAnalyticsKtx = "22.5.0"
firebaseCrashlyticsKtx = "19.4.4"
junit = "4.13.2"
koinAndroid = "4.1.0"
koinCompose = "4.1.0"
kotlin = "2.2.10"
kotlinxCoroutinesCore = "1.10.2"
kotlinxCoroutinesCoreVersion = "1.7.3"
kotlinxDatetime = "0.7.1"
kotlinxDatetimeVersion = "0.5.0"
kotlinxSerializationJson = "1.9.0"
kotlinxSerializationJsonVersion = "1.6.2"
ktorClientCore = "3.2.3"
material3 = "1.3.2"
mpandroidchart = "v3.1.0"
multiplatformSettings = "1.3.0"
napier = "2.7.1"
navigationCompose = "2.9.3"
playServicesAds = "24.5.0"
sqldelight = "2.1.0"
tensorflowLite = "2.17.0"
tensorflowLiteSupport = "0.5.0"
ui = "1.9.0"
workRuntimeKtx = "2.10.3"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "androidDriver" }
android-wave-recorder = { module = "com.github.squti:Android-Wave-Recorder", version.ref = "androidWaveRecorder" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "ui" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
compose-audiowaveform = { module = "com.github.lincollincol:compose-audiowaveform", version.ref = "audioWaveform" }
coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "androidDriver" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebaseAnalyticsKtx" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinAndroid" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinCompose" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientCore" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorClientCore" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClientCore" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "androidDriver" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
runtime = { module = "app.cash.sqldelight:runtime", version.ref = "androidDriver" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLite" }
tensorflow-lite-support = { module = "org.tensorflow:tensorflow-lite-support", version.ref = "tensorflowLiteSupport" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }